const topics = {
    'it': [
        "Internet",
        "Domain",
        "React",
        "JavaScript",
        "HTML",
        "CSS",
        "API",
        "Database",
        "Cloud Computing",
        "Cybersecurity",
        "Artificial Intelligence",
        "Blockchain",
        "Big Data",
        "Responsive Design",
        "Server",
        "Mobile App Development",
        "Version Control",
        "Web Hosting",
        "Network",
        "Encryption",
        "DevOps",
        "Agile Methodology",
        "User Interface (UI)",
        "User Experience (UX)",
        "Frontend Development",
        "Backend Development",
        "Software as a Service (SaaS)",
        "Internet of Things (IoT)",
        "Machine Learning",
        "Data Science",
        "Virtual Reality (VR)",
        "Augmented Reality (AR)",
        "Responsive Web Design",
        "Content Management System (CMS)",
        "E-commerce",
        "Serverless Computing",
        "Shell Scripting",
        "Data Visualization",
        "Programming Paradigms",
        "Continuous Integration/Continuous Deployment (CI/CD)",
        "Microservices",
        "API Gateway",
        "Progressive Web Apps (PWA)",
        "Scalability",
        "Containerization",
        "Server-side Rendering (SSR)",
        "Code Refactoring",
        "Web Accessibility",
        "Cross-platform Development",
        "Data Warehousing",
        "Edge Computing",
        "NoSQL Databases",
        "GraphQL",
        "Single Page Applications (SPA)",
        "Function as a Service (FaaS)",
        "Internet Protocol (IP)",
        "Firewall",
        "Data Mining",
        "Object-Oriented Programming (OOP)",
        "Software Development Life Cycle (SDLC)",
        "MetaPress",
        "Vatom",
        "Google",
        "Apple",
        "Microsoft",
        "Amazon",
        "Facebook",
        "IBM",
        "Intel",
        "Cisco Systems",
        "Oracle",
        "Dell Technologies",
        "Adobe",
        "Salesforce",
        "SAP",
        "HP Inc.",
        "VMware",
        "Nvidia",
        "Twitter",
        "Qualcomm",
        "Accenture",
        "Uber",
        "Airbnb",
        "Netflix",
        "PayPal",
        "Dropbox",
        "Slack Technologies",
        "Zoom Video Communications",
        "LinkedIn",
        "Reddit",
        "Shopify",
        "Tesla",
        "Atlassian",
        "Square",
        "GitHub",
        "Alibaba Group",
        "Tencent",
        "Baidu",
        "Xiaomi",
        "ZoomInfo",
        "Zoho Corporation",
        "Workday",
        "ServiceNow",
        "Twilio",
        "Snowflake",
        "MongoDB",
        "DocuSign",
        "Pinterest",
        "CrowdStrike",
        "Roblox",
    ],
    'movies': [
        "The Shawshank Redemption",
        "The Godfather",
        "The Dark Knight",
        "Schindler's List",
        "Pulp Fiction",
        "The Lord of the Rings: The Return of the King",
        "The Good, the Bad and the Ugly",
        "Fight Club",
        "Forrest Gump",
        "Inception",
        "The Lord of the Rings: The Fellowship of the Ring",
        "Star Wars: Episode V - The Empire Strikes Back",
        "The Matrix",
        "Goodfellas",
        "City of God",
        "The Silence of the Lambs",
        "Seven Samurai",
        "It's a Wonderful Life",
        "Life Is Beautiful",
        "The Usual Suspects",
        "Léon: The Professional",
        "Saving Private Ryan",
        "Spirited Away",
        "The Green Mile",
        "Interstellar",
        "The Pianist",
        "The Departed",
        "Gladiator",
        "The Intouchables",
        "The Prestige",
        "Whiplash",
        "The Lion King",
        "The Godfather: Part II",
        "The Dark Knight Rises",
        "Back to the Future",
        "The Terminator",
        "Alien",
        "The Great Dictator",
        "The Grand Budapest Hotel",
        "Inglourious Basterds",
        "The Truman Show",
        "Amélie",
        "The Shining",
        "The Social Network",
        "The Revenant",
        "Toy Story",
        "The Godfather: Part III",
        "The Wizard of Oz",
        "Avatar",
        "Titanic",
        "Jurassic Park",
        "The Avengers",
        "Finding Nemo",
        "Frozen",
        "Harry Potter and the Sorcerer's Stone",
        "The Sound of Music",
        "E.T. the Extra-Terrestrial",
        "Star Wars: Episode IV - A New Hope",
        "Jaws",
        "Raiders of the Lost Ark",
        "The Exorcist",
        "Grease",
        "The Sixth Sense",
        "Ghostbusters",
        "Shrek",
        "Home Alone",
        "Indiana Jones and the Last Crusade",
        "Batman Begins",
        "Spider-Man",
        "The Hunger Games",
        "The Incredibles",
        "Despicable Me",
        "The Jungle Book",
        "The Matrix Reloaded",
        "The Matrix Revolutions",
        "Transformers",
        "Finding Dory",
        "Harry Potter and the Deathly Hallows – Part 2",
        "The Hobbit: An Unexpected Journey",
        "The Hobbit: The Desolation of Smaug",
        "The Hobbit: The Battle of the Five Armies",
        "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
        "The Chronicles of Narnia: Prince Caspian",
        "The Chronicles of Narnia: The Voyage of the Dawn Treader",
        "The Princess Bride",
        "The Greatest Showman",
        "Tom Hanks",
        "Meryl Streep",
        "Leonardo DiCaprio",
        "Jennifer Lawrence",
        "Brad Pitt",
        "Denzel Washington",
        "Julia Roberts",
        "Johnny Depp",
        "Charlize Theron",
        "Robert De Niro",
        "Natalie Portman",
        "George Clooney",
        "Emma Stone",
        "Matt Damon",
        "Anne Hathaway",
        "Will Smith",
        "Cate Blanchett",
        "Joaquin Phoenix",
        "Nicole Kidman",
        "Tom Cruise",
        "Scarlett Johansson",
        "Christian Bale",
        "Kate Winslet",
        "Chris Hemsworth",
        "Jessica Chastain",
        "Mark Wahlberg",
        "Sandra Bullock",
        "Daniel Day-Lewis",
        "Jennifer Aniston",
        "Samuel L. Jackson",
        "Amy Adams",
        "Hugh Jackman",
        "Rachel McAdams",
        "Ryan Reynolds",
        "Viola Davis",
        "Chris Evans",
        "Emily Blunt",
        "Kevin Hart",
        "Emma Watson",
        "Michael Fassbender",
        "Margot Robbie",
        "Matthew McConaughey",
        "Reese Witherspoon",
        "Ryan Gosling",
        "Robert Downey Jr.",
        "Jennifer Lopez",
        "Ben Affleck",
        "Angelina Jolie",
        "Steven Spielberg",
        "Martin Scorsese",
        "Christopher Nolan",
        "Quentin Tarantino",
        "Alfred Hitchcock",
        "Stanley Kubrick",
        "James Cameron",
        "Francis Ford Coppola",
        "Tim Burton",
        "Steven Soderbergh",
        "Ridley Scott",
        "David Fincher",
        "Spike Lee",
        "Clint Eastwood",
        "Woody Allen",
        "Paul Thomas Anderson",
        "Peter Jackson",
        "Coen Brothers (Joel and Ethan Coen)",
        "Guillermo del Toro",
        "Ron Howard",
        "Blockbuster",
        "Premiere",
        "Red carpet",
        "Box office",
        "Casting",
        "Director",
        "Producer",
        "Screenplay",
        "Audition",
        "Rehearsal",
        "Film festival",
        "Cinematography",
        "Editing",
        "Special effects",
        "Soundtrack",
        "Script",
        "Location scouting",
        "Film crew",
        "Set design",
        "Costume design",
        "Filmography",
        "Casting call",
        "Movie theater",
        "Motion picture",
        "Sequel",
        "Trilogy",
        "Stunt double",
        "CGI (Computer Generated Imagery)",
        "Art direction",
        "Film noir",
        "Genre",
        "Hollywood",
        "Indie film",
        "On-set",
        "Movie magic",
        "Clapperboard",
        "Screenwriter",
        "Film score",
        "Post-production",
        "Opening weekend",
        "Film critic",
        "Movie poster",
        "Screen test",
        "Movie star",
        "Film school",
        "Film industry",
        "Film reel",
        "Movie set",
        "Film buff",
        "Action!"        
    ],
    'music': [
        "Album",
        "Single",
        "Artist",
        "Band",
        "Concert",
        "Tour",
        "Recording",
        "Producer",
        "Songwriter",
        "Musician",
        "Lyrics",
        "Melody",
        "Chorus",
        "Verse",
        "Bridge",
        "Hook",
        "Gig",
        "Venue",
        "Stage",
        "Live performance",
        "Music video",
        "Streaming",
        "Digital distribution",
        "Record label",
        "A&R (Artist and Repertoire)",
        "Hit song",
        "Chart-topping",
        "Billboard",
        "Grammy Awards",
        "MTV",
        "Music producer",
        "Music industry",
        "Sound engineer",
        "Mixing",
        "Mastering",
        "Session musician",
        "Backing vocals",
        "Instrumental",
        "Music festival",
        "Music theory",
        "Music education",
        "Music therapy",
        "Copyright",
        "Royalties",
        "Sampling",
        "Collaboration",
        "Solo artist",
        "Fanbase",
        "Music scene",
        "Encore",
        "The Beatles",
        "Michael Jackson",
        "Elvis Presley",
        "Madonna",
        "Queen",
        "Led Zeppelin",
        "Bob Dylan",
        "David Bowie",
        "Prince",
        "The Rolling Stones",
        "Bob Marley",
        "Beyoncé",
        "Eminem",
        "Adele",
        "Stevie Wonder",
        "Pink Floyd",
        "Whitney Houston",
        "U2",
        "Nirvana",
        "Bruce Springsteen",
        "Taylor Swift",
        "The Eagles",
        "Jimi Hendrix",
        "Frank Sinatra",
        "Coldplay",
        "Metallica",
        "Rihanna",
        "Justin Bieber",
        "Kanye West",
        "The Beach Boys",
        "Mariah Carey",
        "Jay-Z",
        "AC/DC",
        "Bruno Mars",
        "Fleetwood Mac",
        "The Weeknd",
        "Aretha Franklin",
        "Drake",
        "Ed Sheeran",
        "Katy Perry",
        "Guns N' Roses",
        "Pink",
        "John Lennon",
        "Paul McCartney",
        "Lady Gaga",
        "Celine Dion",
        "Elton John",
        "Ariana Grande",
        "Oasis",
        "Rock",
        "Pop",
        "Hip-hop",
        "R&B (Rhythm and Blues)",
        "Jazz",
        "Blues",
        "Country",
        "Electronic",
        "Reggae",
        "Folk",
        "Classical",
        "Heavy Metal",
        "Punk",
        "Funk",
        "Soul",
        "Indie",
        "Alternative",
        "Disco",
        "Gospel",
        "EDM (Electronic Dance Music)",
    ],
    'sport': [
        "Real Madrid (Football)",
        "Manchester United (Football)",
        "FC Barcelona (Football)",
        "Liverpool FC (Football)",
        "New York Yankees (Baseball)",
        "Los Angeles Lakers (Basketball)",
        "Dallas Cowboys (American Football)",
        "New England Patriots (American Football)",
        "Golden State Warriors (Basketball)",
        "Chicago Bulls (Basketball)",
        "New England Revolution (Soccer)",
        "Boston Red Sox (Baseball)",
        "Los Angeles Dodgers (Baseball)",
        "Green Bay Packers (American Football)",
        "Seattle Seahawks (American Football)",
        "Pittsburgh Steelers (American Football)",
        "Boston Celtics (Basketball)",
        "Miami Heat (Basketball)",
        "Los Angeles Rams (American Football)",
        "Manchester City (Football)",
        "Chelsea FC (Football)",
        "Arsenal FC (Football)",
        "Tottenham Hotspur (Football)",
        "Los Angeles Galaxy (Football)",
        "New York Knicks (Basketball)",
        "Brooklyn Nets (Basketball)",
        "San Francisco 49ers (American Football)",
        "Kansas City Chiefs (American Football)",
        "Manchester United (Basketball)",
        "Toronto Raptors (Basketball)",
        "Houston Rockets (Basketball)",
        "New Orleans Saints (American Football)",
        "AC Milan (Football)",
        "Inter Milan (Football)",
        "Juventus FC (Football)",
        "FC Bayern Munich (Football)",
        "Paris Saint-Germain (Football)",
        "Atletico Madrid (Football)",
        "Baltimore Ravens (American Football)",
        "Denver Broncos (American Football)",
        "Indianapolis Colts (American Football)",
        "San Francisco Giants (Baseball)",
        "Chicago Cubs (Baseball)",
        "Los Angeles Angels (Baseball)",
        "Atlanta Braves (Baseball)",
        "Philadelphia Eagles (American Football)",
        "Washington Football Team (American Football)",
        "Buffalo Bills (American Football)",
        "New York Mets (Baseball)",
        "Michael Jordan (Basketball)",
        "Serena Williams (Tennis)",
        "Usain Bolt (Track and Field)",
        "Cristiano Ronaldo (Football)",
        "Lionel Messi (Football)",
        "Muhammad Ali (Boxing)",
        "Roger Federer (Tennis)",
        "Tiger Woods (Golf)",
        "LeBron James (Basketball)",
        "Rafael Nadal (Tennis)",
        "Kobe Bryant (Basketball)",
        "Pele (Football)",
        "Diego Maradona (Football)",
        "Mike Tyson (Boxing)",
        "Megan Rapinoe (Football)",
        "Simone Biles (Gymnastics)",
        "Michael Phelps (Swimming)",
        "Tom Brady (American Football)",
        "Neymar Jr. (Football)",
        "Lindsey Vonn (Skiing)",
        "Coco Gauff (Tennis)",
        "Naomi Osaka (Tennis)",
        "Novak Djokovic (Tennis)",
        "Alex Morgan (Football)",
        "Venus Williams (Tennis)",
        "Carli Lloyd (Football)",
        "Nadia Comaneci (Gymnastics)",
        "Kelly Slater (Surfing)",
        "Laila Ali (Boxing)",
        "Katie Ledecky (Swimming)",
        "Carl Lewis (Track and Field)",
        "Chris Evert (Tennis)",
        "Wayne Gretzky (Ice Hockey)",
        "Caitlyn Jenner (Athletics)",
        "Martina Navratilova (Tennis)",
        "Mia Hamm (Football)",
        "David Beckham (Football)",
        "Manny Pacquiao (Boxing)",
        "Gabby Douglas (Gymnastics)",
        "Allyson Felix (Track and Field)",
        "Shaun White (Snowboarding)",
        "Carolina Marin (Badminton)",
        "Football (Soccer)",
        "Basketball",
        "Tennis",
        "Swimming",
        "Athletics (Track and Field)",
        "Gymnastics",
        "Boxing",
        "Golf",
        "Cricket",
        "Rugby",
        "Baseball",
        "Ice Hockey",
        "Badminton",
        "Cycling",
        "Volleyball",
        "Skiing",
        "Snowboarding",
        "Surfing",
        "Martial Arts",
        "Table Tennis",
        "Goal",
        "Touchdown",
        "Home run",
        "Ace",
        "Field goal",
        "Grand slam",
        "Hat-trick",
        "Medal",
        "Podium",
        "Champion",
        "Runner-up",
        "Finals",
        "Match point",
        "Offside",
        "Timeout",
        "Penalty kick",
        "Free throw",
        "Corner kick",
        "Foul",
        "Yellow card",
        "Red card",
        "Substitution",
        "Referee",
        "Umpire",
        "Coach",
        "Team captain",
        "Half-time",
        "Overtime",
        "Sudden death",
        "League",
        "Division",
        "Conference",
        "World record",
        "Personal best",
        "Training camp",
        "Warm-up",
        "Stretching",
        "Locker room",
        "Injury time",
        "Game plan",
        "Strategy",
        "Tactics",
        "Sportsmanship",
        "Fair play",
        "Fanbase",
        "MVP (Most Valuable Player)",
        "Underdog",
        "Comeback",
        "Victory parade",
        "Sports analytics"        
    ],
    'geography': [
        "Afghanistan",
        "Albania",
        "Algeria",
        "Andorra",
        "Angola",
        "Antigua and Barbuda",
        "Argentina",
        "Armenia",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bhutan",
        "Bolivia",
        "Bosnia and Herzegovina",
        "Botswana",
        "Brazil",
        "Brunei",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Cabo Verde",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Central African Republic",
        "Chad",
        "Chile",
        "China",
        "Colombia",
        "Comoros",
        "Congo",
        "Costa Rica",
        "Croatia",
        "Cuba",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Eswatini",
        "Ethiopia",
        "Fiji",
        "Finland",
        "France",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Greece",
        "Grenada",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Honduras",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Ireland",
        "Israel",
        "Italy",
        "Jamaica",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Mauritania",
        "Mauritius",
        "Mexico",
        "Micronesia",
        "Moldova",
        "Monaco",
        "Mongolia",
        "Montenegro",
        "Morocco",
        "Mozambique",
        "Myanmar",
        "Namibia",
        "Nauru",
        "Nepal",
        "Netherlands",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "North Korea",
        "North Macedonia",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Poland",
        "Portugal",
        "Qatar",
        "Romania",
        "Russia",
        "Rwanda",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Vincent and the Grenadines",
        "Samoa",
        "San Marino",
        "Sao Tome and Principe",
        "Saudi Arabia",
        "Senegal",
        "Serbia",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "Somalia",
        "South Africa",
        "South Korea",
        "South Sudan",
        "Spain",
        "Sri Lanka",
        "Sudan",
        "Suriname",
        "Sweden",
        "Switzerland",
        "Syria",
        "Taiwan",
        "Tajikistan",
        "Tanzania",
        "Thailand",
        "Timor-Leste",
        "Togo",
        "Tonga",
        "Trinidad and Tobago",
        "Tunisia",
        "Turkey",
        "Turkmenistan",
        "Tuvalu",
        "Uganda",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom",
        "United States",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Vatican City",
        "Venezuela",
        "Vietnam",
        "Yemen",
        "Zambia",
        "Zimbabwe"
    ]

}

export default topics