const topics = {
    'it': [
        "Internet",
        "Domain",
        "React",
        "JavaScript",
        "HTML",
        "CSS",
        "API",
        "Database",
        "Cloud Computing",
        "Cybersecurity",
        "Artificial Intelligence",
        "Blockchain",
        "Big Data",
        "Responsive Design",
        "Server",
        "Mobile App Development",
        "Version Control",
        "Web Hosting",
        "Network",
        "Encryption",
        "DevOps",
        "Agile Methodology",
        "User Interface (UI)",
        "User Experience (UX)",
        "Frontend Development",
        "Backend Development",
        "Software as a Service (SaaS)",
        "Internet of Things (IoT)",
        "Machine Learning",
        "Data Science",
        "Virtual Reality (VR)",
        "Augmented Reality (AR)",
        "Responsive Web Design",
        "Content Management System (CMS)",
        "E-commerce",
        "Serverless Computing",
        "Shell Scripting",
        "Data Visualization",
        "Programming Paradigms",
        "Continuous Integration/Continuous Deployment (CI/CD)",
        "Microservices",
        "API Gateway",
        "Progressive Web Apps (PWA)",
        "Scalability",
        "Containerization",
        "Server-side Rendering (SSR)",
        "Code Refactoring",
        "Web Accessibility",
        "Cross-platform Development",
        "Data Warehousing",
        "Edge Computing",
        "NoSQL Databases",
        "GraphQL",
        "Single Page Applications (SPA)",
        "Function as a Service (FaaS)",
        "Internet Protocol (IP)",
        "Firewall",
        "Data Mining",
        "Object-Oriented Programming (OOP)",
        "Software Development Life Cycle (SDLC)",
        "MetaPress",
        "Vatom",
        "Google",
        "Apple",
        "Microsoft",
        "Amazon",
        "Facebook",
        "IBM",
        "Intel",
        "Cisco Systems",
        "Oracle",
        "Dell Technologies",
        "Adobe",
        "Salesforce",
        "SAP",
        "HP Inc.",
        "VMware",
        "Nvidia",
        "Twitter",
        "Qualcomm",
        "Accenture",
        "Uber",
        "Airbnb",
        "Netflix",
        "PayPal",
        "Dropbox",
        "Slack Technologies",
        "Zoom Video Communications",
        "LinkedIn",
        "Reddit",
        "Shopify",
        "Tesla",
        "Atlassian",
        "Square",
        "GitHub",
        "Alibaba Group",
        "Tencent",
        "Baidu",
        "Xiaomi",
        "ZoomInfo",
        "Zoho Corporation",
        "Workday",
        "ServiceNow",
        "Twilio",
        "Snowflake",
        "MongoDB",
        "DocuSign",
        "Pinterest",
        "CrowdStrike",
        "Roblox",
    ],
    'movies': [
        "The Shawshank Redemption",
        "The Godfather",
        "The Dark Knight",
        "Schindler's List",
        "Pulp Fiction",
        "The Lord of the Rings: The Return of the King",
        "The Good, the Bad and the Ugly",
        "Fight Club",
        "Forrest Gump",
        "Inception",
        "The Lord of the Rings: The Fellowship of the Ring",
        "Star Wars: Episode V - The Empire Strikes Back",
        "The Matrix",
        "Goodfellas",
        "City of God",
        "The Silence of the Lambs",
        "Seven Samurai",
        "It's a Wonderful Life",
        "Life Is Beautiful",
        "The Usual Suspects",
        "Léon: The Professional",
        "Saving Private Ryan",
        "Spirited Away",
        "The Green Mile",
        "Interstellar",
        "The Pianist",
        "The Departed",
        "Gladiator",
        "The Intouchables",
        "The Prestige",
        "Whiplash",
        "The Lion King",
        "The Godfather: Part II",
        "The Dark Knight Rises",
        "Back to the Future",
        "The Terminator",
        "Alien",
        "The Great Dictator",
        "The Grand Budapest Hotel",
        "Inglourious Basterds",
        "The Truman Show",
        "Amélie",
        "The Shining",
        "The Social Network",
        "The Revenant",
        "Toy Story",
        "The Godfather: Part III",
        "The Wizard of Oz",
        "Avatar",
        "Titanic",
        "Jurassic Park",
        "The Avengers",
        "Finding Nemo",
        "Frozen",
        "Harry Potter and the Sorcerer's Stone",
        "The Sound of Music",
        "E.T. the Extra-Terrestrial",
        "Star Wars: Episode IV - A New Hope",
        "Jaws",
        "Raiders of the Lost Ark",
        "The Exorcist",
        "Grease",
        "The Sixth Sense",
        "Ghostbusters",
        "Shrek",
        "Home Alone",
        "Indiana Jones and the Last Crusade",
        "Batman Begins",
        "Spider-Man",
        "The Hunger Games",
        "The Incredibles",
        "Despicable Me",
        "The Jungle Book",
        "The Matrix Reloaded",
        "The Matrix Revolutions",
        "Transformers",
        "Finding Dory",
        "Harry Potter and the Deathly Hallows – Part 2",
        "The Hobbit: An Unexpected Journey",
        "The Hobbit: The Desolation of Smaug",
        "The Hobbit: The Battle of the Five Armies",
        "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
        "The Chronicles of Narnia: Prince Caspian",
        "The Chronicles of Narnia: The Voyage of the Dawn Treader",
        "The Princess Bride",
        "The Greatest Showman",
        "Tom Hanks",
        "Meryl Streep",
        "Leonardo DiCaprio",
        "Jennifer Lawrence",
        "Brad Pitt",
        "Denzel Washington",
        "Julia Roberts",
        "Johnny Depp",
        "Charlize Theron",
        "Robert De Niro",
        "Natalie Portman",
        "George Clooney",
        "Emma Stone",
        "Matt Damon",
        "Anne Hathaway",
        "Will Smith",
        "Cate Blanchett",
        "Joaquin Phoenix",
        "Nicole Kidman",
        "Tom Cruise",
        "Scarlett Johansson",
        "Christian Bale",
        "Kate Winslet",
        "Chris Hemsworth",
        "Jessica Chastain",
        "Mark Wahlberg",
        "Sandra Bullock",
        "Daniel Day-Lewis",
        "Jennifer Aniston",
        "Samuel L. Jackson",
        "Amy Adams",
        "Hugh Jackman",
        "Rachel McAdams",
        "Ryan Reynolds",
        "Viola Davis",
        "Chris Evans",
        "Emily Blunt",
        "Kevin Hart",
        "Emma Watson",
        "Michael Fassbender",
        "Margot Robbie",
        "Matthew McConaughey",
        "Reese Witherspoon",
        "Ryan Gosling",
        "Robert Downey Jr.",
        "Jennifer Lopez",
        "Ben Affleck",
        "Angelina Jolie",
        "Steven Spielberg",
        "Martin Scorsese",
        "Christopher Nolan",
        "Quentin Tarantino",
        "Alfred Hitchcock",
        "Stanley Kubrick",
        "James Cameron",
        "Francis Ford Coppola",
        "Tim Burton",
        "Steven Soderbergh",
        "Ridley Scott",
        "David Fincher",
        "Spike Lee",
        "Clint Eastwood",
        "Woody Allen",
        "Paul Thomas Anderson",
        "Peter Jackson",
        "Coen Brothers (Joel and Ethan Coen)",
        "Guillermo del Toro",
        "Ron Howard",
        "Blockbuster",
        "Premiere",
        "Red carpet",
        "Box office",
        "Casting",
        "Director",
        "Producer",
        "Screenplay",
        "Audition",
        "Rehearsal",
        "Film festival",
        "Cinematography",
        "Editing",
        "Special effects",
        "Soundtrack",
        "Script",
        "Location scouting",
        "Film crew",
        "Set design",
        "Costume design",
        "Filmography",
        "Casting call",
        "Movie theater",
        "Motion picture",
        "Sequel",
        "Trilogy",
        "Stunt double",
        "CGI (Computer Generated Imagery)",
        "Art direction",
        "Film noir",
        "Genre",
        "Hollywood",
        "Indie film",
        "On-set",
        "Movie magic",
        "Clapperboard",
        "Screenwriter",
        "Film score",
        "Post-production",
        "Opening weekend",
        "Film critic",
        "Movie poster",
        "Screen test",
        "Movie star",
        "Film school",
        "Film industry",
        "Film reel",
        "Movie set",
        "Film buff",
        "Action!"        
    ],
    'music': [
        "Album",
        "Single",
        "Artist",
        "Band",
        "Concert",
        "Tour",
        "Recording",
        "Producer",
        "Songwriter",
        "Musician",
        "Lyrics",
        "Melody",
        "Chorus",
        "Verse",
        "Bridge",
        "Hook",
        "Gig",
        "Venue",
        "Stage",
        "Live performance",
        "Music video",
        "Streaming",
        "Digital distribution",
        "Record label",
        "A&R (Artist and Repertoire)",
        "Hit song",
        "Chart-topping",
        "Billboard",
        "Grammy Awards",
        "MTV",
        "Music producer",
        "Music industry",
        "Sound engineer",
        "Mixing",
        "Mastering",
        "Session musician",
        "Backing vocals",
        "Instrumental",
        "Music festival",
        "Music theory",
        "Music education",
        "Music therapy",
        "Copyright",
        "Royalties",
        "Sampling",
        "Collaboration",
        "Solo artist",
        "Fanbase",
        "Music scene",
        "Encore",
        "The Beatles",
        "Michael Jackson",
        "Elvis Presley",
        "Madonna",
        "Queen",
        "Led Zeppelin",
        "Bob Dylan",
        "David Bowie",
        "Prince",
        "The Rolling Stones",
        "Bob Marley",
        "Beyoncé",
        "Eminem",
        "Adele",
        "Stevie Wonder",
        "Pink Floyd",
        "Whitney Houston",
        "U2",
        "Nirvana",
        "Bruce Springsteen",
        "Taylor Swift",
        "The Eagles",
        "Jimi Hendrix",
        "Frank Sinatra",
        "Coldplay",
        "Metallica",
        "Rihanna",
        "Justin Bieber",
        "Kanye West",
        "The Beach Boys",
        "Mariah Carey",
        "Jay-Z",
        "AC/DC",
        "Bruno Mars",
        "Fleetwood Mac",
        "The Weeknd",
        "Aretha Franklin",
        "Drake",
        "Ed Sheeran",
        "Katy Perry",
        "Guns N' Roses",
        "Pink",
        "John Lennon",
        "Paul McCartney",
        "Lady Gaga",
        "Celine Dion",
        "Elton John",
        "Ariana Grande",
        "Oasis",
        "Rock",
        "Pop",
        "Hip-hop",
        "R&B (Rhythm and Blues)",
        "Jazz",
        "Blues",
        "Country",
        "Electronic",
        "Reggae",
        "Folk",
        "Classical",
        "Heavy Metal",
        "Punk",
        "Funk",
        "Soul",
        "Indie",
        "Alternative",
        "Disco",
        "Gospel",
        "EDM (Electronic Dance Music)",
    ],
    'sport': [
        "Real Madrid (Football)",
        "Manchester United (Football)",
        "FC Barcelona (Football)",
        "Liverpool FC (Football)",
        "New York Yankees (Baseball)",
        "Los Angeles Lakers (Basketball)",
        "Dallas Cowboys (American Football)",
        "New England Patriots (American Football)",
        "Golden State Warriors (Basketball)",
        "Chicago Bulls (Basketball)",
        "New England Revolution (Soccer)",
        "Boston Red Sox (Baseball)",
        "Los Angeles Dodgers (Baseball)",
        "Green Bay Packers (American Football)",
        "Seattle Seahawks (American Football)",
        "Pittsburgh Steelers (American Football)",
        "Boston Celtics (Basketball)",
        "Miami Heat (Basketball)",
        "Los Angeles Rams (American Football)",
        "Manchester City (Football)",
        "Chelsea FC (Football)",
        "Arsenal FC (Football)",
        "Tottenham Hotspur (Football)",
        "Los Angeles Galaxy (Football)",
        "New York Knicks (Basketball)",
        "Brooklyn Nets (Basketball)",
        "San Francisco 49ers (American Football)",
        "Kansas City Chiefs (American Football)",
        "Manchester United (Basketball)",
        "Toronto Raptors (Basketball)",
        "Houston Rockets (Basketball)",
        "New Orleans Saints (American Football)",
        "AC Milan (Football)",
        "Inter Milan (Football)",
        "Juventus FC (Football)",
        "FC Bayern Munich (Football)",
        "Paris Saint-Germain (Football)",
        "Atletico Madrid (Football)",
        "Baltimore Ravens (American Football)",
        "Denver Broncos (American Football)",
        "Indianapolis Colts (American Football)",
        "San Francisco Giants (Baseball)",
        "Chicago Cubs (Baseball)",
        "Los Angeles Angels (Baseball)",
        "Atlanta Braves (Baseball)",
        "Philadelphia Eagles (American Football)",
        "Washington Football Team (American Football)",
        "Buffalo Bills (American Football)",
        "New York Mets (Baseball)",
        "Michael Jordan (Basketball)",
        "Serena Williams (Tennis)",
        "Usain Bolt (Track and Field)",
        "Cristiano Ronaldo (Football)",
        "Lionel Messi (Football)",
        "Muhammad Ali (Boxing)",
        "Roger Federer (Tennis)",
        "Tiger Woods (Golf)",
        "LeBron James (Basketball)",
        "Rafael Nadal (Tennis)",
        "Kobe Bryant (Basketball)",
        "Pele (Football)",
        "Diego Maradona (Football)",
        "Mike Tyson (Boxing)",
        "Megan Rapinoe (Football)",
        "Simone Biles (Gymnastics)",
        "Michael Phelps (Swimming)",
        "Tom Brady (American Football)",
        "Neymar Jr. (Football)",
        "Lindsey Vonn (Skiing)",
        "Coco Gauff (Tennis)",
        "Naomi Osaka (Tennis)",
        "Novak Djokovic (Tennis)",
        "Alex Morgan (Football)",
        "Venus Williams (Tennis)",
        "Carli Lloyd (Football)",
        "Nadia Comaneci (Gymnastics)",
        "Kelly Slater (Surfing)",
        "Laila Ali (Boxing)",
        "Katie Ledecky (Swimming)",
        "Carl Lewis (Track and Field)",
        "Chris Evert (Tennis)",
        "Wayne Gretzky (Ice Hockey)",
        "Caitlyn Jenner (Athletics)",
        "Martina Navratilova (Tennis)",
        "Mia Hamm (Football)",
        "David Beckham (Football)",
        "Manny Pacquiao (Boxing)",
        "Gabby Douglas (Gymnastics)",
        "Allyson Felix (Track and Field)",
        "Shaun White (Snowboarding)",
        "Carolina Marin (Badminton)",
        "Football (Soccer)",
        "Basketball",
        "Tennis",
        "Swimming",
        "Athletics (Track and Field)",
        "Gymnastics",
        "Boxing",
        "Golf",
        "Cricket",
        "Rugby",
        "Baseball",
        "Ice Hockey",
        "Badminton",
        "Cycling",
        "Volleyball",
        "Skiing",
        "Snowboarding",
        "Surfing",
        "Martial Arts",
        "Table Tennis",
        "Goal",
        "Touchdown",
        "Home run",
        "Ace",
        "Field goal",
        "Grand slam",
        "Hat-trick",
        "Medal",
        "Podium",
        "Champion",
        "Runner-up",
        "Finals",
        "Match point",
        "Offside",
        "Timeout",
        "Penalty kick",
        "Free throw",
        "Corner kick",
        "Foul",
        "Yellow card",
        "Red card",
        "Substitution",
        "Referee",
        "Umpire",
        "Coach",
        "Team captain",
        "Half-time",
        "Overtime",
        "Sudden death",
        "League",
        "Division",
        "Conference",
        "World record",
        "Personal best",
        "Training camp",
        "Warm-up",
        "Stretching",
        "Locker room",
        "Injury time",
        "Game plan",
        "Strategy",
        "Tactics",
        "Sportsmanship",
        "Fair play",
        "Fanbase",
        "MVP (Most Valuable Player)",
        "Underdog",
        "Comeback",
        "Victory parade",
        "Sports analytics"        
    ],
    'geography': [
        "Afghanistan",
        "Albania",
        "Algeria",
        "Andorra",
        "Angola",
        "Antigua and Barbuda",
        "Argentina",
        "Armenia",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bhutan",
        "Bolivia",
        "Bosnia and Herzegovina",
        "Botswana",
        "Brazil",
        "Brunei",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Cabo Verde",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Central African Republic",
        "Chad",
        "Chile",
        "China",
        "Colombia",
        "Comoros",
        "Congo",
        "Costa Rica",
        "Croatia",
        "Cuba",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Eswatini",
        "Ethiopia",
        "Fiji",
        "Finland",
        "France",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Greece",
        "Grenada",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Honduras",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Ireland",
        "Israel",
        "Italy",
        "Jamaica",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Mauritania",
        "Mauritius",
        "Mexico",
        "Micronesia",
        "Moldova",
        "Monaco",
        "Mongolia",
        "Montenegro",
        "Morocco",
        "Mozambique",
        "Myanmar",
        "Namibia",
        "Nauru",
        "Nepal",
        "Netherlands",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "North Korea",
        "North Macedonia",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Poland",
        "Portugal",
        "Qatar",
        "Romania",
        "Russia",
        "Rwanda",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Vincent and the Grenadines",
        "Samoa",
        "San Marino",
        "Sao Tome and Principe",
        "Saudi Arabia",
        "Senegal",
        "Serbia",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "Somalia",
        "South Africa",
        "South Korea",
        "South Sudan",
        "Spain",
        "Sri Lanka",
        "Sudan",
        "Suriname",
        "Sweden",
        "Switzerland",
        "Syria",
        "Taiwan",
        "Tajikistan",
        "Tanzania",
        "Thailand",
        "Timor-Leste",
        "Togo",
        "Tonga",
        "Trinidad and Tobago",
        "Tunisia",
        "Turkey",
        "Turkmenistan",
        "Tuvalu",
        "Uganda",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom",
        "United States",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Vatican City",
        "Venezuela",
        "Vietnam",
        "Yemen",
        "Zambia",
        "Zimbabwe"
    ],
    'history': [
        "World War I",
        "World War II",
        "Cold War",
        "The Great Depression",
        "French Revolution",
        "American Revolution",
        "Industrial Revolution",
        "Magna Carta",
        "Renaissance",
        "Enlightenment",
        "Ancient Egypt",
        "Ancient Greece",
        "Ancient Rome",
        "Byzantine Empire",
        "The Crusades",
        "The Black Death",
        "The Age of Exploration",
        "The Silk Road",
        "The Fall of Constantinople",
        "The Spanish Inquisition",
        "The Protestant Reformation",
        "The Age of Discovery",
        "The Age of Enlightenment",
        "The Age of Imperialism",
        "The Russian Revolution",
        "The Great Fire of London",
        "The Salem Witch Trials",
        "The Trail of Tears",
        "The Holocaust",
        "The Civil Rights Movement",
        "The Vietnam War",
        "The Korean War",
        "The American Civil War",
        "The French and Indian War",
        "The Battle of Waterloo",
        "The Cuban Missile Crisis",
        "The Space Race",
        "The Renaissance",
        "The Scientific Revolution",
        "The Berlin Wall",
        "The Louisiana Purchase",
        "The Boston Tea Party",
        "The Emancipation Proclamation",
        "The Declaration of Independence",
        "The Treaty of Versailles",
        "The Battle of Gettysburg",
        "The Great Famine",
        "The D-Day Invasion",
        "The Manhattan Project",
        "The Marshall Plan",
        "The Lewis and Clark Expedition",
        "The Oregon Trail",
        "The Gold Rush",
        "The Alamo",
        "The Battle of Bunker Hill",
        "The Battle of Saratoga",
        "The Battle of Bull Run",
        "The Battle of Vicksburg",
        "The Battle of Little Bighorn",
        "The Battle of Yorktown",
        "The Treaty of Ghent",
        "The Treaty of Guadalupe Hidalgo",
        "The Treaty of Paris (1898)",
        "The Treaty of Portsmouth",
        "The Treaty of Trianon",
        "The Treaty of Brest-Litovsk",
        "The Treaty of Nanking",
        "The Treaty of Utrecht",
        "The Treaty of Kanagawa",
        "The Treaty of Waitangi",
        "The Treaty of San Francisco",
        "The Treaty of London (1915)",
        "The Treaty of Saint-Germain-en-Laye",
        "The Treaty of Westphalia",
        "The Treaty of Paris (1783)",
        "The Treaty of Vienna",
        "The Treaty of Rome (1957)",
        "The Treaty of Paris (1951)",
        "The Treaty of Berlin (1878)",
        "The Treaty of Nice",
        "The Treaty of Lisbon",
        "The Treaty of Maastricht",
        "The Treaty of Amiens",
        "The Treaty of Rapallo",
        "The Treaty of Compiègne",
        "The Treaty of Zurich",
        "The Treaty of Ryswick",
        "The Treaty of Tordesillas",
        "The Treaty of Madrid",
        "The Treaty of Guernsey",
        "The Treaty of Aix-la-Chapelle",
        "The Treaty of Locarno",
        "The Treaty of Gdansk",
        "The Treaty of Sevres",
        "The Roaring Twenties",
        "The Great Migration",
        "The Dust Bowl",
        "The New Deal",
        "The Great Society",
        "The Atomic Bomb",
        "The Hiroshima and Nagasaki bombings",
        "The Civil Rights Act of 1964",
        "The Voting Rights Act of 1965",
        "The Monroe Doctrine",
        "The Articles of Confederation",
        "The Battle of Antietam",
        "The Battle of Normandy",
        "The Battle of Stalingrad",
        "The Battle of Midway",
        "The Fall of the Berlin Wall",
        "The Berlin Airlift",
        "The Red Scare",
        "The Watergate Scandal",
        "The Assassination of Abraham Lincoln",
        "The Assassination of John F. Kennedy",
        "The Bay of Pigs Invasion",
        "The Tet Offensive",
        "The Siege of Leningrad",
        "The Siege of Yorktown",
        "The Spanish Armada",
        "The Boxer Rebellion",
        "Cleopatra",
        "Julius Caesar",
        "Alexander the Great",
        "Napoleon Bonaparte",
        "Genghis Khan",
        "Queen Elizabeth I",
        "William Shakespeare",
        "Christopher Columbus",
        "George Washington",
        "Nelson Mandela",
        "Mahatma Gandhi",
        "Abraham Lincoln",
        "Joan of Arc",
        "Martin Luther King Jr.",
        "Albert Einstein",
        "Leonardo da Vinci",
        "Sir Isaac Newton",
        "Alexander Hamilton",
        "Karl Marx",
        "Adolf Hitler",
        "Winston Churchill",
        "Thomas Jefferson",
        "Socrates",
        "Galileo Galilei",
        "Michelangelo",
        "Vincent van Gogh",
        "Benjamin Franklin",
        "Queen Victoria",
        "Ronald Reagan",
        "Henry Ford",
        "Gandhi",
        "Malcolm X",
        "Margaret Thatcher",
        "Marie Curie",
        "Rosa Parks",
        "Florence Nightingale",
        "Amelia Earhart",
        "Sir Francis Drake",
        "Marco Polo",
        "Charles Darwin",
        "Wright Brothers",
        "Steve Jobs",
        "Joseph Stalin",
        "Mao Zedong",
        "Confucius",
        "Emperor Qin Shi Huang",
        "Gautama Buddha",
        "Aristotle",
        "Gaius Marius",
        "Augustus Caesar",
        "Charlemagne",
        "William the Conqueror",
        "Vladimir Lenin",
        "Josef Stalin",
        "Leon Trotsky",
        "Francisco Pizarro",
        "Hernán Cortés",
        "Suleiman the Magnificent",
        "Catherine the Great",
        "Peter the Great",
        "William the Silent",
        "Michel de Montaigne",
        "Voltaire",
        "Jean-Jacques Rousseau",
        "Immanuel Kant",
        "Adam Smith",
        "Otto von Bismarck",
        "Mary, Queen of Scots",
        "Louis XIV",
        "Louis XVI",
        "Marie Antoinette",
        "Robespierre",
        "Frederick the Great",
        "John Locke",
        "Thomas Hobbes",
        "Niccolò Machiavelli",
        "Pope Leo X",
        "Queen Isabella I",
        "King Ferdinand II",
        "Saladin",
        "Richard the Lionheart",
        "El Cid"
    ],
    'television': [
        "Drama series",
        "Reality TV",
        "Game show",
        "Crime drama",
        "Soap opera",
        "Talk show",
        "Variety show",
        "Documentary series",
        "Animated series",
        "Miniseries",
        "Late-night show",
        "Sketch comedy",
        "Science fiction series",
        "Fantasy series",
        "Mystery series",
        "Historical drama",
        "Sitcom pilot",
        "Musical variety show",
        "True crime series",
        "Cooking show",
        "Travel show",
        "DIY show",
        "Competition show",
        "Talent show",
        "Courtroom drama",
        "Medical drama",
        "Superhero series",
        "Sitcom finale",
        "Police procedural",
        "Adventure series",
        "Sitcom reboot",
        "Animated sitcom",
        "Comedy-drama",
        "Teen drama",
        "Romance series",
        "Family sitcom",
        "Period drama",
        "Survival show",
        "Home renovation show",
        "Educational program",
        "Sports talk show",
        "Animated adventure",
        "Political drama",
        "Satirical comedy",
        "Reality competition",
        "Mystery thriller",
        "Sitcom spin-off",
        "Cooking competition",
        "Travel documentary",
        "Jennifer Aniston",
        "Tom Hanks",
        "Bryan Cranston",
        "Julia Louis-Dreyfus",
        "Jon Hamm",
        "Viola Davis",
        "Hugh Laurie",
        "Tina Fey",
        "Kiefer Sutherland",
        "Maggie Smith",
        "Steve Carell",
        "Sarah Jessica Parker",
        "Kit Harington",
        "Ellen Pompeo",
        "Alec Baldwin",
        "Betty White",
        "David Duchovny",
        "Sophie Turner",
        "Matthew Fox",
        "Amy Poehler",
        "Julianna Margulies",
        "Larry David",
        "Gillian Anderson",
        "Ted Danson",
        "Kerry Washington",
        "Jason Bateman",
        "Gina Rodriguez",
        "Charlie Sheen",
        "Emily Deschanel",
        "Andy Samberg",
        "Kaley Cuoco",
        "Gina Torres",
        "James Spader",
        "Shonda Rhimes",
        "Hugh Bonneville",
        "Angela Lansbury",
        "Michael C. Hall",
        "Zooey Deschanel",
        "Neil Patrick Harris",
        "Ellen DeGeneres",
        "Nathan Fillion",
        "Mariska Hargitay",
        "Lisa Kudrow",
        "David Schwimmer",
        "Courteney Cox",
        "Matt LeBlanc",
        "Jesse Tyler Ferguson",
        "Ty Burrell",
        "Lena Headey",
        "Jon Cryer",
        "Emily Bett Rickards",
        "Jeffrey Tambor",
        "Connie Britton",
        "Katherine Heigl",
        "Idris Elba",
        "Tatiana Maslany",
        "Hugh Grant",
        "Phoebe Waller-Bridge",
        "Kristen Bell",
        "Andy Griffith",
        "Lily Tomlin",
        "Freddie Highmore",
        "Anthony Anderson",
        "Ellie Kemper",
        "Patrick Dempsey",
        "America Ferrera",
        "Mandy Moore",
        "Donald Glover",
        "Julia Roberts",
        "Keri Russell",
        "Mark Harmon",
        "Shemar Moore",
        "Sarah Michelle Gellar",
        "Tim Allen",
        "Dan Levy",
        "Lana Parrilla",
        "Cote de Pablo",
        "Sandra Oh",
        "David Boreanaz",
        "Lana Condor",
        "Dominic West",
        "Michael Weatherly",
        "Shailene Woodley",
        "Eric Stonestreet",
        "Milo Ventimiglia",
        "Jane Lynch",
        "Kristen Wiig",
        "Blake Lively",
        "Dennis Franz",
        "Seth MacFarlane",
        "Hugh Dancy",
        "Kristen Johnston",
        "Peter Dinklage",
        "Katey Sagal",
        "Debra Messing",
        "Eric McCormack",
        "Jennifer Love Hewitt",
        "Chris O'Donnell",
        "Jeff Goldblum",
        "Rami Malek",
        "Will Arnett",
        "Kyle Chandler",
        "Rachel Brosnahan",
        "Tituss Burgess",
        "Gillian Jacobs",
        "Timothy Olyphant",
        "Alyssa Milano",
        "Felicity Huffman",
        "John Goodman",
        "Robin Wright",
        "Amanda Seyfried",
        "Aaron Paul",
        "Billy Bob Thornton",
        "Brie Larson",
        "Evan Rachel Wood",
        "Edie Falco",
        "Christina Hendricks",
        "Charlie Hunnam",
        "Martin Sheen",
        "Sophia Bush",
        "Ed O'Neill",
        "Lauren Graham",
        "Rob Lowe",
        "Teri Hatcher",
        "Marcia Cross",
        "Eva Longoria",
        "Zach Braff",
        "Jessica Biel",
        "Game of Thrones",
        "Breaking Bad",
        "Friends",
        "The Office (US)",
        "Stranger Things",
        "The Crown",
        "The Mandalorian",
        "Grey's Anatomy",
        "The Simpsons",
        "The Big Bang Theory",
        "Fargo",
        "Black Mirror",
        "The Marvelous Mrs. Maisel",
        "The Handmaid's Tale",
        "The Walking Dead",
        "Mindhunter",
        "The Sopranos",
        "Westworld",
        "Better Call Saul",
        "Sherlock",
        "Parks and Recreation",
        "Doctor Who",
        "Narcos",
        "The Witcher",
        "Peaky Blinders",
        "Brooklyn Nine-Nine",
        "The Good Place",
        "House of Cards",
        "Modern Family",
        "Lost",
        "Downton Abbey",
        "How I Met Your Mother",
        "The X-Files",
        "The Twilight Zone",
        "The West Wing",
        "The Office (UK)",
        "The Americans",
        "The Leftovers",
        "The Umbrella Academy",
        "The Vampire Diaries",
        "The Wire",
        "Twin Peaks",
        "True Detective",
        "Vikings",
        "Watchmen",
        "When They See Us",
        "Yellowstone",
        "You",
        "Young Sheldon",
        "American Horror Story",
        "Arrested Development",
        "Atlanta",
        "Bates Motel",
        "Big Little Lies",
        "BoJack Horseman",
        "Broadchurch",
        "Chernobyl",
        "Cobra Kai",
        "Dead to Me",
        "Desperate Housewives",
        "Fear the Walking Dead",
        "Fleabag",
        "Friday Night Lights",
        "Full House",
        "Glee",
        "Gossip Girl",
        "Hannibal",
        "Homeland",
        "House",
        "How to Get Away with Murder",
        "Lucifer",
        "Mad Men",
        "Marvel's Daredevil",
        "Master of None",
        "Mr. Robot",
        "New Girl",
        "Orange Is the New Black"
    ],
    'literature': [
        "Novel",
        "Poetry",
        "Short story",
        "Drama",
        "Fiction",
        "Non-fiction",
        "Prose",
        "Sonnet",
        "Epic",
        "Sonnet",
        "Haiku",
        "Satire",
        "Comedy",
        "Tragedy",
        "Romance",
        "Mystery",
        "Fantasy",
        "Science fiction",
        "Historical fiction",
        "Autobiography",
        "Biography",
        "Memoir",
        "Classic literature",
        "Modern literature",
        "Literary criticism",
        "Symbolism",
        "Allegory",
        "Metaphor",
        "Simile",
        "Imagery",
        "Alliteration",
        "Irony",
        "Foreshadowing",
        "Flashback",
        "Characterization",
        "Plot",
        "Setting",
        "Theme",
        "Conflict",
        "Resolution",
        "Point of view",
        "First-person narrative",
        "Third-person narrative",
        "Omniscient narrator",
        "Stream of consciousness",
        "Bildungsroman",
        "Dystopian fiction",
        "Gothic literature",
        "Magical realism",
        "Existentialism",
        "William Shakespeare",
        "Jane Austen",
        "Charles Dickens",
        "Mark Twain",
        "Leo Tolstoy",
        "George Orwell",
        "J.K. Rowling",
        "Ernest Hemingway",
        "F. Scott Fitzgerald",
        "Virginia Woolf",
        "T.S. Eliot",
        "Emily Dickinson",
        "Homer",
        "Gabriel Garcia Marquez",
        "Harper Lee",
        "Arthur Conan Doyle",
        "John Steinbeck",
        "Agatha Christie",
        "Mary Shelley",
        "Stephen King",
        "J.R.R. Tolkien",
        "Hermann Hesse",
        "Dante Alighieri",
        "Edgar Allan Poe",
        "Toni Morrison",
        "Franz Kafka",
        "William Faulkner",
        "H.G. Wells",
        "Aldous Huxley",
        "Margaret Atwood",
        "Albert Camus",
        "George R.R. Martin",
        "Jack Kerouac",
        "H.P. Lovecraft",
        "Daphne du Maurier",
        "Kurt Vonnegut",
        "Ralph Waldo Emerson",
        "J.D. Salinger",
        "Nathaniel Hawthorne",
        "Henry James",
        "H.G. Wells",
        "Walt Whitman",
        "Oscar Wilde",
        "John Milton",
        "Emily Bronte",
        "Robert Frost",
        "George Eliot",
        "Ernest Hemingway",
        "James Joyce",
        "Louisa May Alcott",
        "To Kill a Mockingbird"
        "1984",
        "Pride and Prejudice",
        "The Great Gatsby",
        "Moby-Dick",
        "War and Peace",
        "The Catcher in the Rye",
        "One Hundred Years of Solitude",
        "The Lord of the Rings",
        "Jane Eyre",
        "The Grapes of Wrath",
        "Catch-22",
        "Anna Karenina",
        "Wuthering Heights",
        "Brave New World",
        "The Hobbit",
        "Crime and Punishment",
        "The Adventures of Huckleberry Finn",
        "The Brothers Karamazov",
        "Don Quixote",
        "The Picture of Dorian Gray",
        "The Scarlet Letter",
        "Frankenstein",
        "Gone with the Wind",
        "Les Misérables",
        "The Count of Monte Cristo",
        "Alice's Adventures in Wonderland",
        "Lord of the Flies",
        "The Odyssey",
        "A Tale of Two Cities",
        "The Canterbury Tales",
        "Dracula",
        "The Iliad",
        "Great Expectations",
        "The Stranger",
        "The Divine Comedy",
        "The Trial",
        "The Sun Also Rises",
        "Heart of Darkness",
        "Walden",
        "The Bell Jar",
        "The Old Man and the Sea",
        "A Clockwork Orange",
        "The Handmaid's Tale",
        "A Farewell to Arms",
        "The Sound and the Fury",
        "The Outsiders",
        "Slaughterhouse-Five",
        "On the Road",
        "The Chronicles of Narnia",
        "The Godfather",
        "The Wind-Up Bird Chronicle",
        "The Girl with the Dragon Tattoo",
        "The Road",
        "The Stand",
        "The Da Vinci Code",
        "The Name of the Rose",
        "The Silence of the Lambs",
        "The Goldfinch",
        "The Martian",
        "The Alchemist",
        "The Night Circus",
        "The Help",
        "The Kite Runner",
        "The Lovely Bones",
        "The Secret History",
        "The Pillars of the Earth",
        "The Thorn Birds",
        "The Book Thief",
        "The Shining",
        "The Hand That First Held Mine",
        "The Poisonwood Bible",
        "The Time Traveler's Wife",
        "The Secret Garden",
        "The Guernsey Literary and Potato Peel Pie Society",
        "The Nightingale",
        "The Color Purple",
        "The Cider House Rules",
        "The Giver",
        "The Sisterhood of the Traveling Pants",
        "The Secret Life of Bees",
        "The Immortal Life of Henrietta Lacks",
        "The Glass Castle",
        "The Brief Wondrous Life of Oscar Wao",
        "The Underground Railroad",
        "The Light Between Oceans",
        "The Great Alone",
        "The Orphan Master's Son",
        "The Rosie Project",
        "The Seven Husbands of Evelyn Hugo",
        "The Silent Patient",
        "Man's Search for Meaning",
        "The Diary of a Young Girl",
        "The Immortal Life of Henrietta Lacks",
        "In Cold Blood",
        "Silent Spring",
        "The Autobiography of Malcolm X",
        "The Feminine Mystique",
        "The Audacity of Hope",
        "The Elements of Style",
        "The Art of War",
        "The Tipping Point",
        "Outliers",
        "The Omnivore's Dilemma",
        "Freakonomics",
        "The Power of Habit",
        "How to Win Friends and Influence People",
        "The 7 Habits of Highly Effective People",
        "Blink",
        "Thinking, Fast and Slow",
        "Born to Run",
        "Steve Jobs",
        "The Wright Brothers",
        "The Sixth Extinction",
        "Educated",
        "Sapiens: A Brief History of Humankind",
        "Quiet: The Power of Introverts in a World That Can't Stop Talking",
        "Into Thin Air",
        "Guns, Germs, and Steel",
        "The Emperor of All Maladies",
        "The Immortal Life of Henrietta Lacks",
        "Fast Food Nation",
        "The Omnivore's Dilemma",
        "The Warmth of Other Suns",
        "Just Mercy",
        "The New Jim Crow",
        "Between the World and Me",
        "Hillbilly Elegy",
        "Evicted",
        "Bad Blood: Secrets and Lies in a Silicon Valley Startup",
        "The Glass Castle",
        "The Boys in the Boat",
        "Unbroken",
        "Walden",
        "The Federalist Papers",
        "The Origin of Species",
        "The Wealth of Nations",
        "The Prince",
        "The Communist Manifesto",
        "Manufacturing Consent",
        "The Art of Happiness",
        "Into the Wild",
        "Wild: From Lost to Found on the Pacific Crest Trail",
        "Born a Crime"
    ],
    'gaming': [
        "Video game",
        "Console gaming",
        "PC gaming",
        "Mobile gaming",
        "Online gaming",
        "Multiplayer gaming",
        "Single-player gaming",
        "Role-playing game (RPG)",
        "First-person shooter (FPS)",
        "Battle royale",
        "Open-world game",
        "Strategy game",
        "Simulation game",
        "Adventure game",
        "Platformer",
        "Action game",
        "Sports game",
        "Racing game",
        "Fighting game",
        "Horror game",
        "Survival game",
        "MMORPG (Massively Multiplayer Online Role-Playing Game)",
        "MOBA (Multiplayer Online Battle Arena)",
        "RTS (Real-Time Strategy)",
        "ARPG (Action Role-Playing Game)",
        "Sandbox game",
        "Indie game",
        "Free-to-play (F2P)",
        "Microtransactions",
        "Downloadable content (DLC)",
        "Virtual reality (VR) gaming",
        "Augmented reality (AR) gaming",
        "Cloud gaming",
        "E-sports",
        "Twitch streaming",
        "Let's Play",
        "Speedrunning",
        "Game development",
        "Game design",
        "Game engine",
        "Gamification",
        "LAN party",
        "Game modding",
        "Emulator",
        "Cheats and hacks",
        "Gamertag",
        "Achievements",
        "Leaderboards",
        "Quest",
        "Level up",
        "Respawn",
        "Game over",
        "Super Mario",
        "Link (Legend of Zelda)",
        "Master Chief (Halo)",
        "Solid Snake (Metal Gear Solid)",
        "Kratos (God of War)",
        "Cloud Strife (Final Fantasy VII)",
        "Sonic the Hedgehog",
        "Lara Croft (Tomb Raider)",
        "Pac-Man",
        "Mega Man",
        "Donkey Kong",
        "Samus Aran (Metroid)",
        "Arthur Morgan (Red Dead Redemption)",
        "Geralt of Rivia (The Witcher)",
        "Ezio Auditore (Assassin's Creed)",
        "Nathan Drake (Uncharted)",
        "Commander Shepard (Mass Effect)",
        "Ellie (The Last of Us)",
        "Aloy (Horizon Zero Dawn)",
        "Doomguy (DOOM)",
        "Scorpion (Mortal Kombat)",
        "Cortana (Halo)",
        "Sora (Kingdom Hearts)",
        "Bayonetta",
        "Crash Bandicoot",
        "Batman (Batman: Arkham series)",
        "Sub-Zero (Mortal Kombat)",
        "Sephiroth (Final Fantasy VII)",
        "Princess Zelda",
        "Dante (Devil May Cry)",
        "Sackboy (LittleBigPlanet)",
        "Spyro the Dragon",
        "Agent 47 (Hitman)",
        "Joel (The Last of Us)",
        "CJ (Grand Theft Auto: San Andreas)",
        "Chun-Li (Street Fighter)",
        "Glados (Portal)",
        "Isaac Clarke (Dead Space)",
        "Leon Kennedy (Resident Evil)",
        "Trevor Philips (Grand Theft Auto V)",
        "Max Payne",
        "John Marston (Red Dead Redemption)",
        "Clementine (The Walking Dead)",
        "Marcus Fenix (Gears of War)",
        "The Legend of Zelda: Breath of the Wild",
        "The Witcher 3: Wild Hunt",
        "Red Dead Redemption 2",
        "Grand Theft Auto V",
        "The Elder Scrolls V: Skyrim",
        "Super Mario Odyssey",
        "God of War (2018)",
        "Minecraft",
        "Fortnite",
        "Among Us",
        "Call of Duty: Warzone",
        "Animal Crossing: New Horizons",
        "Dark Souls III",
        "Persona 5",
        "Assassin's Creed Odyssey",
        "Overwatch",
        "League of Legends",
        "Counter-Strike: Global Offensive",
        "Apex Legends",
        "FIFA 21",
        "Rocket League",
        "Mortal Kombat 11",
        "Super Smash Bros. Ultimate",
        "Cyberpunk 2077",
        "The Last of Us Part II",
        "Final Fantasy VII Remake",
        "Doom Eternal",
        "Ghost of Tsushima",
        "Valorant",
        "Battlefield V",
        "Hades",
        "Cuphead",
        "Terraria",
        "Rainbow Six Siege",
        "Genshin Impact",
        "The Sims 4",
        "Halo: The Master Chief Collection",
        "Resident Evil 7: Biohazard",
        "Death Stranding",
        "Control",
        "Marvel's Spider-Man",
        "Destiny 2",
        "No Man's Sky",
        "The Outer Worlds",
        "Stardew Valley",
        "Persona 5",
        "Horizon Zero Dawn",
        "The Legend of Zelda: Twilight Princess",
        "Bloodborne",
        "Sea of Thieves",
        "Star Wars Jedi: Fallen Order",
        "Tom Clancy's Rainbow Six Siege",
        "Tom Clancy's Splinter Cell",
        "The Elder Scrolls Online",
        "Assassin's Creed Valhalla",
        "Battlefield 2042",
        "Destiny 2",
        "Sea of Thieves",
        "Star Wars Jedi: Fallen Order",
        "Tom Clancy's The Division 2",
        "Tom Clancy's Ghost Recon Breakpoint",
        "Tom Clancy's Ghost Recon Wildlands",
        "Tom Clancy's Rainbow Six Extraction",
        "Tom Clancy's Splinter Cell: Blacklist",
        "Tom Clancy's Splinter Cell: Conviction",
        "Tom Clancy's Splinter Cell: Double Agent",
        "Tom Clancy's Splinter Cell: Chaos Theory",
        "Tom Clancy's Splinter Cell: Pandora Tomorrow",
        "The Elder Scrolls Online",
        "The Elder Scrolls V: Skyrim",
        "Mortal Kombat 11",
        "Super Smash Bros. Ultimate",
        "Persona 5",
        "Death Stranding",
        "Control",
        "DOOM Eternal",
        "Monster Hunter: World",
        "Devil May Cry 5",
        "Among Us",
        "Animal Crossing: New Horizons",
        "Terraria",
        "Stardew Valley",
        "Hollow Knight",
        "Undertale",
        "Celeste",
        "Cuphead",
        "Ori and the Blind Forest",
        "Ori and the Will of the Wisps",
        "Hades",
        "Subnautica",
        "Subnautica: Below Zero",
        "Sekiro: Shadows Die Twice",
        "Bloodborne",
        "Dark Souls III",
        "Nioh 2",
        "Ghost of Tsushima",
        "God of War",
        "Marvel's Spider-Man",
        "Demon's Souls",
        "Resident Evil Village",
        "Persona 5 Royal",
        "NieR: Automata",
        "Disco Elysium",
        "The Outer Worlds",
        "Fallout 4",
        "Fallout: New Vegas",
        "Super Mario Odyssey",
        "Luigi's Mansion 3",
        "Mario Kart 8 Deluxe",
        "The Legend of Zelda: Link's Awakening",
        "Fire Emblem: Three Houses",
        "Pokémon Sword and Shield",
        "Splatoon 2",
        "Octopath Traveler",
        "Xenoblade Chronicles: Definitive Edition"
    ]

}

export default topics